### ISSUE TITLE
Installation in a conda environment.

### ISSUE THREAD

**Issue by IrribarraC** [pearsonkyle/Exoplanet-Light-Curve-Analysis#1]
Hey, I'm trying to install this package inside an environment, followed your instructions but doesn't seem to work. I'm kind of unexperienced on managing environments and would really love your help.

**Comment by pearsonkyle** [comment]
I have this package installed in a conda environment but you will have to install it manually. I don't have it packed up for anaconda, so you can't do like a "conda install ...." . Were you able to follow the instructions at the bottom of the readme? If there's a specific step that's not working I can help you a little more from there. 

If it's not importing then it probably has to do with how you set your path. What type of system are you installing this on? Mac? or Linux?
