### ISSUE TITLE
UltraNest support

### ISSUE THREAD

**Issue by JohannesBuchner** [pearsonkyle/Exoplanet-Light-Curve-Analysis#20]
Would you be interested to add support for https://johannesbuchner.github.io/UltraNest/ ?
The interface should be very similar to dynesty.
UltraNest is a very reliable tuning-parameter-free algorithm. It can be faster than dynesty, especially if you take advantage of vectorization.
It also supports resuming from disk and MPI parallelisation, if that is useful to you.

**Comment by pearsonkyle** [comment]
@JohannesBuchner  Thanks for bringing this up, I've been a fan since the days of multinest. I've replaced dynesty and ultranest works much faster. Thanks for making the install easier!

**Comment by pearsonkyle** [comment]
On a side note, we're using ultranest for all of these model fits: https://exoplanets.nasa.gov/exoplanet-watch/results/

**Comment by JohannesBuchner** [comment]
Amazing!
